name: 'Check for new Snyk issues'
description: 'This is an action that checks if there are new license or vulnerability issues compared to a baseline project.'

inputs:
  snyk-args:
    default: ""
    required: false
    description: "Arguments passed to the Snyk test command"
  artifact-name:
    default: "snyk-report"
    required: false
    description: "The name of the Snyk report generated"
  snyk-token:
    required: true
    description: "The token used to authenticate with Snyk"
  github-username:
    default: ""
    required: false
    description: "GitHub username"
  github-token:
    default: ""
    required: false
    description: "GitHub token"
  enterprise-access-key:
    default: ""
    required: false
    description: "HiveMQ Enterprise Access Key"
  enterprise-secret-key:
    default: ""
    required: false
    description: "HiveMQ Enterprise Secret Key"
  snyk-baseline-project-id:
    default: ""
    required: false
    description: "ID of project that is used as a baseline"
  snyk-api-version:
    default: "2024-09-04"
    required: false
    description: "Snyk API version to use"

runs:
  using: composite
  steps:
    - name: Setup Snyk
      uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04 # v1

    - name: Run Snyk to check for vulnerabilities
      id: snyk_test
      shell: bash
      run: |
        echo "::group::Snyk summary"
        snyk test ${{ inputs.snyk-args }} --print-deps --json --json-file-output=snyk.json >> snyk-debug.log 2>&1
        echo "::endgroup::"
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        ORG_GRADLE_PROJECT_hivemqCommonsUsername: ${{ inputs.github-username }}
        ORG_GRADLE_PROJECT_hivemqCommonsPassword: ${{ inputs.github-token }}
        ORG_GRADLE_PROJECT_hivemqEnterpriseAccessKey: ${{ inputs.enterprise-access-key }}
        ORG_GRADLE_PROJECT_hivemqEnterpriseSecretKey: ${{ inputs.enterprise-secret-key }}
      continue-on-error: true

    - name: Validate Snyk output
      id: validate_snyk
      shell: bash
      run: |
        if [ ! -f snyk.json ]; then
          echo "::error::snyk.json was not created. Snyk test likely failed to run."
          echo
          echo "DEBUG snyk test:"
          cat snyk-debug.log
          exit 1
        fi
        if ! jq empty snyk.json 2>/dev/null; then
          echo "::error::snyk.json is not valid JSON."
          echo
          echo "DEBUG snyk test:"
          cat snyk-debug.log
          echo
          echo "DEBUG snyk.json:"
          cat snyk.json
          exit 1
        fi
        snyk_org=$(jq -r '.org // empty' < snyk.json)
        snyk_project_name=$(jq -r '.projectName // empty' < snyk.json)
        if [ -z "$snyk_org" ] || [ -z "$snyk_project_name" ]; then
          echo "::error::snyk.json is missing required fields (org or projectName)."
          echo
          echo "DEBUG snyk test:"
          cat snyk-debug.log
          echo
          echo "DEBUG snyk.json:"
          cat snyk.json
          exit 1
        fi

    - name: Get Snyk attributes
      shell: bash
      run: |
        echo "snyk_org=$(jq -r '.org' < snyk.json)" >> "$GITHUB_ENV"
        echo "snyk_project_name=$(jq -r '.projectName' < snyk.json)" >> "$GITHUB_ENV"
        echo "snyk_target_file=$(jq -r '.targetFile' < snyk.json)" >> "$GITHUB_ENV"

    - name: Get Snyk org ID
      id: get_snyk_org_id
      uses: fjogeleit/http-request-action@551353b829c3646756b2ec2b3694f819d7957495 # v2
      with:
        url: 'https://api.snyk.io/rest/orgs?version=${{ inputs.snyk-api-version }}&slug=${{ env.snyk_org }}'
        method: 'GET'
        customHeaders: '{"Authorization": "token ${{ inputs.snyk-token }}"}'
        retry: 3

    - name: Calculate project name query
      id: calculate_project_name_query
      shell: bash
      run: |
        project_name_query="${{ env.snyk_project_name }}"
        retrieved_target_file="${{ env.snyk_target_file }}"
        if [ "${retrieved_target_file}" != "null" ]; then
          project_name_query="${project_name_query}%3A${retrieved_target_file}"
        fi
        echo "project_name_query=${project_name_query}" >> "$GITHUB_OUTPUT"

    - name: Get baseline project ID
      id: get_baseline_project_id
      uses: fjogeleit/http-request-action@551353b829c3646756b2ec2b3694f819d7957495 # v2
      with:
        url: 'https://api.snyk.io/rest/orgs/${{ fromJson(steps.get_snyk_org_id.outputs.response).data[0].id }}/projects?version=${{ inputs.snyk-api-version }}&target_reference=${{ github.base_ref }}&names=${{ steps.calculate_project_name_query.outputs.project_name_query }}'
        method: 'GET'
        customHeaders: '{"Authorization": "token ${{ inputs.snyk-token }}"}'
        retry: 3

    - name: Choose baseline project ID
      id: choose_baseline_project_id
      shell: bash
      run: |
        response_data='${{ toJson(fromJson(steps.get_baseline_project_id.outputs.response).data) }}'
        if [ "$(echo "$response_data" | jq 'length')" -gt 0 ]; then
          retrieved_baseline_project_id="$(echo "$response_data" | jq -r '.[0].id')"
        else
          retrieved_baseline_project_id=""
        fi
        echo "snyk_baseline_project_id=${retrieved_baseline_project_id:-${{ inputs.snyk-baseline-project-id }}}" >> "$GITHUB_OUTPUT"

    - name: Get ignored issues
      id: get_ignored_issues
      uses: fjogeleit/http-request-action@551353b829c3646756b2ec2b3694f819d7957495 # v2
      with:
        url: 'https://api.snyk.io/rest/orgs/${{ fromJson(steps.get_snyk_org_id.outputs.response).data[0].id }}/issues?version=${{ inputs.snyk-api-version }}&limit=100&ignored=true&scan_item.id=${{ steps.choose_baseline_project_id.outputs.snyk_baseline_project_id }}&scan_item.type=project'
        method: 'GET'
        customHeaders: '{"Authorization": "token ${{ inputs.snyk-token }}"}'
        responseFile: 'ignored_issues_${{ env.snyk_project_name }}.json'
        retry: 3

    - name: Create ignore file based on already ignored issues
      id: create_ignore_file
      shell: bash
      run: |
        snyk auth ${{ inputs.snyk-token }}
        mkdir ${{ env.snyk_project_name }}-policy
        jq '.data[] | .attributes.key' ignored_issues_${{ env.snyk_project_name }}.json | while read issue_id; do
          snyk ignore --id=$issue_id --policy-path=${{ env.snyk_project_name }}-policy
        done

    - name: Run Snyk with the snyk ignore file
      shell: bash
      run: snyk test ${{ inputs.snyk-args }} --print-deps --json --json-file-output=snyk.json --policy-path=${{ env.snyk_project_name }}-policy >> snyk-debug.log 2>&1
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        ORG_GRADLE_PROJECT_hivemqCommonsUsername: ${{ inputs.github-username }}
        ORG_GRADLE_PROJECT_hivemqCommonsPassword: ${{ inputs.github-token }}
        ORG_GRADLE_PROJECT_hivemqEnterpriseAccessKey: ${{ inputs.enterprise-access-key }}
        ORG_GRADLE_PROJECT_hivemqEnterpriseSecretKey: ${{ inputs.enterprise-secret-key }}
      continue-on-error: true

    - name: Set up node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: '20'

    - name: Install and run snyk-to-html
      shell: bash
      run: |
        npm i -g snyk-to-html
        snyk-to-html -i snyk.json -o ${{ inputs.artifact-name }}.html

    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ inputs.artifact-name }}
        path: | 
          ${{ inputs.artifact-name }}.html
          snyk-debug.log

    - name: Install snyk-delta and dependencies
      shell: bash
      run: npm i -g snyk-delta@1.12.7

    - name: Check delta
      shell: bash
      run: |
        set +e
        snyk_delta_args=(--type vuln)
        snyk_baseline_project_id="${{ steps.choose_baseline_project_id.outputs.snyk_baseline_project_id }}"
        if [ -n "$snyk_baseline_project_id" ]; then
          snyk_delta_args+=(--baselineProject $snyk_baseline_project_id)
        fi
        cat snyk.json | snyk-delta "${snyk_delta_args[@]}"
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
            if [ $exit_code -eq 1 ]; then
              echo "::error ::New issues were found! For more info, refer to the Snyk report found in the Artifacts section of the job summary."
            fi
            exit $exit_code
        fi
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        ORG_GRADLE_PROJECT_hivemqCommonsUsername: ${{ inputs.github-username }}
        ORG_GRADLE_PROJECT_hivemqCommonsPassword: ${{ inputs.github-token }}
        ORG_GRADLE_PROJECT_hivemqEnterpriseAccessKey: ${{ inputs.enterprise-access-key }}
        ORG_GRADLE_PROJECT_hivemqEnterpriseSecretKey: ${{ inputs.enterprise-secret-key }}
